# Generated by Django 3.2.13 on 2022-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20221005_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feautre_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
